---
stats_dir: '/pscratch/sd/f/feng045/usa/gridrad_v3/stats/'
pixelfile_dir: '/pscratch/sd/f/feng045/usa/gridrad_v3/'
tc_file: '/global/cfs/cdirs/m1867/zfeng/gpm/IBTrACS/ibtracs_NA_2004_2022.nc'
mcsstats_filebase: 'mcs_tracks_final_'
# mcsstats_filebase: 'mcs_tracks_final_extc_'
pixel_filebase: 'mcstrack_'
landmask_file: '/pscratch/sd/f/feng045/usa/gridrad_v3/map_data/mergir4km_grid_terrain_landmask.nc'
output_dir: '/pscratch/sd/f/feng045/usa/gridrad_v3/stats/'
output_monthly_dir: '/pscratch/sd/f/feng045/usa/gridrad_v3/stats/monthly/'
output_daily_dir: '/pscratch/sd/f/feng045/usa/gridrad_v3/stats/daily/'
output_climo_dir: '/pscratch/sd/f/feng045/usa/gridrad_v3/stats/climo/'
# Precipitation variable name
pcpvarname: 'precipitation'
# Movement variable names in MCS track stats
# varname_speed: 'movement_r_meters_per_second'
varname_speed: 'movement_speed'
varname_mov_x: 'movement_distance_x'
varname_mov_y: 'movement_distance_y'
# Dask workers and threads
run_parallel: 1
n_workers: 128
threads_per_worker: 1
# Rain rate threshold to define a PF [mm/h]
rr_min: 1.0
# Pixel size [km]
pixel_radius: 4.0  
# Minimum PF area threshold [km^2]
pf_min_area_thresh: 0
# # Threshold of pixel-level land fraction to define a land pixel [%]
# landfrac_thresh: 90
# List of years to calculate climatology
climo_years: [2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017]
# climo_years: [2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021]